#!/bin/bash

readonly SQL_INIT_SCRIPT="packages/pfa-influxr/build/pro_football_analytics.sql"

container_name="pro-football-analytics_postgres_1"
if [ "${1}" ]; then
	container_name="${1}"
fi

echo "Copying seed data into ${container_name} container"
docker cp "${SQL_INIT_SCRIPT}" "${container_name}":/tmp

echo "Seeding database"
docker exec "${container_name}" psql -h localhost \
                                -p 5432 \
                                -d pro_football_analytics \
                                -U pfa_master \
                                -f /tmp/pro_football_analytics.sql